
package accountBalance.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.1
 * Tue Mar 22 19:37:40 CET 2022
 * Generated source version: 3.5.1
 */

@XmlRootElement(name = "getAccountBalanceResponse", namespace = "http://accountBalance/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getAccountBalanceResponse", namespace = "http://accountBalance/")

public class GetAccountBalanceResponse {

    @XmlElement(name = "return")
    private double _return;

    public double getReturn() {
        return this._return;
    }

    public void setReturn(double new_return)  {
        this._return = new_return;
    }

}

