
package tut01;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-22T22:04:13.965+01:00
 * Generated source version: 3.5.1
 *
 */
public final class Receipt_ReceiptImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://tut01/", "ReceiptService");

    private Receipt_ReceiptImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ReceiptService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ReceiptService ss = new ReceiptService(wsdlURL, SERVICE_NAME);
        Receipt port = ss.getReceiptImplPort();

        {
        System.out.println("Invoking makePDF...");
        int _makePDF_arg0 = 555;
        java.lang.String _makePDF__return = port.makePDF(_makePDF_arg0);
        System.out.println("makePDF.result=" + _makePDF__return);


        }
        {
        System.out.println("Invoking priceDPH...");
        int _priceDPH_arg0 = 20228025;
        int _priceDPH_arg1 = 10;
        double _priceDPH__return = port.priceDPH(_priceDPH_arg0, _priceDPH_arg1);
        System.out.println("priceDPH.result=" + _priceDPH__return);


        }

        System.exit(0);
    }

}
