package tut01;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-22T22:04:14.048+01:00
 * Generated source version: 3.5.1
 *
 */
@WebService(targetNamespace = "http://tut01/", name = "Receipt")
@XmlSeeAlso({ObjectFactory.class})
public interface Receipt {

    @WebMethod(action = "http://tut01/Receipt/makePDF")
    @RequestWrapper(localName = "makePDF", targetNamespace = "http://tut01/", className = "tut01.MakePDF")
    @ResponseWrapper(localName = "makePDFResponse", targetNamespace = "http://tut01/", className = "tut01.MakePDFResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String makePDF(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod(action = "http://tut01/Receipt/priceDPH")
    @RequestWrapper(localName = "priceDPH", targetNamespace = "http://tut01/", className = "tut01.PriceDPH")
    @ResponseWrapper(localName = "priceDPHResponse", targetNamespace = "http://tut01/", className = "tut01.PriceDPHResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double priceDPH(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
