package tut01;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-22T22:04:14.053+01:00
 * Generated source version: 3.5.1
 *
 */
@WebServiceClient(name = "ReceiptService",
                  wsdlLocation = "file:/D:/Skola/1.Mgr/LS/ReceiptWSDL.xml",
                  targetNamespace = "http://tut01/")
public class ReceiptService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tut01/", "ReceiptService");
    public final static QName ReceiptImplPort = new QName("http://tut01/", "ReceiptImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Skola/1.Mgr/LS/ReceiptWSDL.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ReceiptService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/Skola/1.Mgr/LS/ReceiptWSDL.xml");
        }
        WSDL_LOCATION = url;
    }

    public ReceiptService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ReceiptService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReceiptService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ReceiptService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ReceiptService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ReceiptService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Receipt
     */
    @WebEndpoint(name = "ReceiptImplPort")
    public Receipt getReceiptImplPort() {
        return super.getPort(ReceiptImplPort, Receipt.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Receipt
     */
    @WebEndpoint(name = "ReceiptImplPort")
    public Receipt getReceiptImplPort(WebServiceFeature... features) {
        return super.getPort(ReceiptImplPort, Receipt.class, features);
    }

}
